import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import CircularProgress from '@mui/material/CircularProgress'
import { Activity, ArrowRight, ArrowUpRight, CalendarDays, ChevronDown, FileText, Handshake, Plus, ShieldCheck, Sparkles } from 'lucide-react'

export function DashboardView({
  todayLabel, greeting, userName, pendingValue, openProposals, acceptedValue, accepted,
  acceptanceRate, upcomingCount, dataLoading, proposals, ProposalTable, setSelected,
  setCreateOpen, openNav, pipelineStages, maxPipeline, notify,
}) {
  return <>
    <div className="welcome-row"><div><span className="eyebrow"><span className="eyebrow-dot" /> {todayLabel}</span><h1>{greeting}, {userName.split(' ')[0]} <span className="wave">✳</span></h1><p>Suas boas conversas podem virar bons projetos. Veja o que está acontecendo.</p></div><Button className="btn-primary" onClick={() => setCreateOpen(true)}><Plus size={17} /> Nova proposta</Button></div>
    <div className="stats-grid">
      <Card component="article" className="stat-card"><div className="stat-top"><span>Em propostas abertas</span><span className="stat-icon icon-lilac"><FileText size={16} /></span></div><strong>{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(pendingValue)}</strong><div className="stat-foot"><span className="stat-trend"><ArrowUpRight size={13} /> {openProposals.length} propostas</span><span>aguardando retorno</span></div></Card>
      <Card component="article" className="stat-card"><div className="stat-top"><span>Valor aceito</span><span className="stat-icon icon-mint"><Handshake size={16} /></span></div><strong>{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(acceptedValue)}</strong><div className="stat-foot"><span className="stat-trend trend-green"><ArrowUpRight size={13} /> {accepted.length} aceitas</span><span>nesta carteira</span></div></Card>
      <Card component="article" className="stat-card"><div className="stat-top"><span>Taxa de aceite</span><span className="stat-icon icon-amber"><Activity size={16} /></span></div><strong>{acceptanceRate}<small>%</small></strong><div className="stat-foot"><span>propostas enviadas ou concluídas</span></div><div className="rate-track"><span style={{ width: acceptanceRate + '%' }} /></div></Card>
      <Card component="article" className="stat-card"><div className="stat-top"><span>Próximos vencimentos</span><span className="stat-icon icon-blue"><CalendarDays size={16} /></span></div><strong>{upcomingCount.toString().padStart(2, '0')}</strong><div className="stat-foot"><span>Nos próximos 7 dias</span><span className="stat-reminder"><i /> atenção</span></div></Card>
    </div>
    <div className="dashboard-grid"><Card component="section" className="panel recent-panel"><div className="panel-heading"><div><h2>Propostas recentes</h2><p>Acompanhe as conversas que estão em andamento.</p></div><Button className="text-action" onClick={() => openNav('propostas')}>Ver todas <ArrowRight size={14} /></Button></div><div className="table-scroll">{dataLoading ? <div className="dashboard-empty" role="status"><CircularProgress size={17} /> Carregando propostas do Supabase...</div> : proposals.length ? <ProposalTable proposals={proposals.slice(0, 5)} onOpen={setSelected} /> : <div className="dashboard-empty"><span>Nenhuma proposta cadastrada neste espaço.</span><Button className="text-action" onClick={() => setCreateOpen(true)}>Criar proposta <ArrowRight size={14} /></Button></div>}</div><Button className="mobile-see-all" onClick={() => openNav('propostas')}>Ver todas as propostas <ArrowRight size={14} /></Button></Card>
      <aside className="right-rail"><Card component="section" className="panel pipeline-panel"><div className="panel-heading"><div><h2>Seu pipeline</h2><p>Valor por etapa das propostas</p></div><Button className="small-select" onClick={() => openNav('resultados')}>Carteira <ChevronDown size={12} /></Button></div><div className="pipeline-chart"><div className="chart-y"><span>100%</span><span>75%</span><span>50%</span><span>0%</span></div><div className="chart-columns">{pipelineStages.map((bar) => <div className="chart-column" key={bar.label}><div className="chart-track"><span className={'chart-bar ' + bar.bar} style={{ height: (bar.value ? Math.max(8, (bar.value / maxPipeline) * 90) : 0) + '%' }} title={bar.label} aria-label={bar.label} /></div><small>{bar.label}</small></div>)}</div></div><div className="pipeline-legend"><span><i className="legend-open" /> Em andamento</span><strong>{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(pendingValue)}</strong></div><div className="pipeline-legend"><span><i className="legend-accepted" /> Aceitas</span><strong>{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(acceptedValue)}</strong></div></Card>
        <section className="nudge-card"><span className="nudge-orb"><Sparkles size={16} /></span><div><small>UM BOM PRÓXIMO PASSO</small><strong>Retome uma conversa com o cliente</strong><p>Um acompanhamento gentil pode destravar a conversa.</p><Button onClick={() => openNav('propostas')}>Acompanhar propostas <ArrowRight size={13} /></Button></div><span className="nudge-decoration">✳</span></section><div className="trust-note"><ShieldCheck size={15} /><span>Suas propostas são salvas no espaço de trabalho do Supabase.</span></div></aside></div>
  </>
}

