import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import { ArrowRight, CalendarDays, CheckCircle2, ChevronLeft, Clock3, Download, FileCheck2, FileSignature, ShieldCheck, WalletCards } from 'lucide-react'
import { longDate, money, proposalScope } from '../lib/proposal-domain'
import { Brand, Status } from './common-ui'

export function ClientProposal({ proposal, onSign, onBack, onPdf }) {
  const scope = proposalScope(proposal)
  const expired = proposal.status === 'Expirada'
  return <main className="client-page"><header className="client-top"><Button className="client-brand-button" onClick={onBack} aria-label="Voltar para FechaProposta"><Brand /></Button><span><ShieldCheck size={15} /> Proposta compartilhada com você</span></header>
    <div className="client-proposal-layout"><Card component="article" className="client-document">
      <div className="client-doc-head"><span className="eyebrow">PROPOSTA COMERCIAL <i>·</i> {proposal.id}</span><Status value={proposal.status} /></div>
      <p className="client-greeting">Olá, {proposal.client.split(' ')[0]}.</p><h1>{proposal.title}</h1>
      <section className="client-objective"><span className="client-section-kicker">OBJETIVO DO PROJETO</span><p>{proposal.summary}</p></section>
      <div className="client-meta"><div><span>PREPARADA PARA</span><strong>{proposal.client}</strong></div><div><span>PRAZO ESTIMADO</span><strong>{scope.timeline}</strong></div><div><span>VÁLIDA ATÉ</span><strong>{longDate(proposal.due)}</strong></div></div>
      <section className="client-scope"><div className="client-section-heading"><span className="client-section-icon"><CheckCircle2 size={17} /></span><div><span className="client-section-kicker">ESCOPO</span><h2>O que será feito</h2></div></div><p className="client-section-copy">Estas são as etapas e entregas previstas para o projeto.</p><ol>{scope.deliverables.map((deliverable, index) => <li key={index}><span>{String(index + 1).padStart(2, '0')}</span><strong>{deliverable}</strong></li>)}</ol></section>
      <section className="client-items"><div className="client-section-heading"><span className="client-section-icon money-icon"><WalletCards size={17} /></span><div><span className="client-section-kicker">INVESTIMENTO</span><h2>Valores por etapa</h2></div></div>{proposal.items.map((item, index) => <div className="client-item" key={index}><span><b>{item.name}</b><small>{item.qty} × {money(item.price)} por unidade</small></span><strong>{money(item.qty * item.price)}</strong></div>)}<div className="client-grand-total"><span>Investimento total</span><strong>{money(proposal.amount)}</strong></div><p className="client-tax-note">Valores em reais. {proposal.terms || ''}</p></section>
      <section className="client-conditions"><div className="client-section-heading"><span className="client-section-icon terms-icon"><FileCheck2 size={17} /></span><div><span className="client-section-kicker">COMBINADOS</span><h2>Condições do projeto</h2></div></div><p>{proposal.terms || 'As condições de pagamento e o cronograma serão combinados antes do início do projeto.'}</p>{scope.notIncluded && <div className="client-exclusions"><strong>Fora deste escopo</strong><span>{scope.notIncluded}</span></div>}</section>
      <section className="client-next-step"><span className="client-next-icon"><ArrowRight size={16} /></span><div><span className="client-section-kicker">DEPOIS DO ACEITE</span><h2>Próximo passo</h2><p>{scope.nextStep}</p></div></section>
      <p className="client-document-footnote"><ShieldCheck size={14} /> Leia todas as entregas, valores e condições antes de confirmar sua decisão.</p>
    </Card>
    <Card component="aside" className="client-decision-card"><span className="client-decision-kicker">RESUMO DA PROPOSTA</span><h2>{proposal.title}</h2><div className="decision-total"><span>Investimento total</span><strong>{money(proposal.amount)}</strong></div><div className="decision-meta"><span><CalendarDays size={15} /> Válida até {longDate(proposal.due)}</span><span><Clock3 size={15} /> {scope.timeline}</span></div>{proposal.status === 'Aceita' ? <div className="accepted-panel"><CheckCircle2 size={22} /><div><strong>Proposta aceita</strong><span>{proposal.signedBy ? 'Assinada por ' + proposal.signedBy : 'Aceite registrado'}{proposal.signedAt ? ' · ' + new Date(proposal.signedAt).toLocaleString('pt-BR') : ''}</span></div></div> : expired ? <div className="expired-panel"><Clock3 size={17} /><span>Esta proposta expirou. Entre em contato com quem enviou para solicitar uma nova versão.</span></div> : <><p className="decision-note">Ao aceitar, você confirma que leu o escopo e as condições descritas nesta proposta.</p><Button className="btn-primary client-sign-cta" onClick={() => onSign(proposal)}><FileSignature size={16} /> Assinar e aceitar proposta</Button></>}<Button className="client-pdf-action" onClick={() => onPdf(proposal)}><Download size={15} /> Salvar proposta em PDF</Button><p className="client-demo-note">Este registro de aceite não substitui uma assinatura eletrônica certificada.</p></Card></div>
    <Button className="client-back" onClick={onBack}><ChevronLeft size={15} /> Voltar</Button></main>
}

