import Button from '@mui/material/Button'
import { ArrowRight, CheckCircle2, FileCheck2, ShieldCheck, WalletCards } from 'lucide-react'
import { longDate } from '../lib/proposal-domain'
import { Modal, Status } from './common-ui'

export function ProposalPreview({ clientPreview, previewScope, money, onClose, onSign }) {
  if (!clientPreview) return null
  return (
    <Modal title="Visualização para o cliente" eyebrow="LINK DA PROPOSTA" onClose={onClose} wide className="preview-modal"><div className="preview-banner"><ShieldCheck size={15} /><span>Confira a proposta completa como o cliente vai receber.</span></div><div className="preview-document"><div className="client-doc-head"><span className="eyebrow">PROPOSTA COMERCIAL · {clientPreview.id}</span><Status value={clientPreview.status} /></div><p className="client-greeting">Olá, {clientPreview.client.split(' ')[0]}.</p><h1>{clientPreview.title}</h1><section className="client-objective"><span className="client-section-kicker">OBJETIVO DO PROJETO</span><p>{clientPreview.summary}</p></section><div className="client-meta"><div><span>PREPARADA PARA</span><strong>{clientPreview.client}</strong></div><div><span>PRAZO ESTIMADO</span><strong>{previewScope.timeline}</strong></div><div><span>VÁLIDA ATÉ</span><strong>{longDate(clientPreview.due)}</strong></div></div><section className="client-scope"><div className="client-section-heading"><span className="client-section-icon"><CheckCircle2 size={17} /></span><div><span className="client-section-kicker">ESCOPO</span><h2>O que será feito</h2></div></div><ol>{previewScope.deliverables.map((item, index) => <li key={index}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item}</strong></li>)}</ol></section><section className="client-items"><div className="client-section-heading"><span className="client-section-icon money-icon"><WalletCards size={17} /></span><div><span className="client-section-kicker">INVESTIMENTO</span><h2>Valores por etapa</h2></div></div>{clientPreview.items.map((item, index) => <div className="client-item" key={index}><span><b>{item.name}</b><small>{item.qty} × {money(item.price)} por unidade</small></span><strong>{money(item.qty * item.price)}</strong></div>)}<div className="client-grand-total"><span>Investimento total</span><strong>{money(clientPreview.amount)}</strong></div></section><section className="client-conditions"><div className="client-section-heading"><span className="client-section-icon terms-icon"><FileCheck2 size={17} /></span><div><span className="client-section-kicker">COMBINADOS</span><h2>Condições do projeto</h2></div></div><p>{clientPreview.terms || 'As condições serão combinadas antes do início do projeto.'}</p>{previewScope.notIncluded && <div className="client-exclusions"><strong>Fora deste escopo</strong><span>{previewScope.notIncluded}</span></div>}</section><section className="client-next-step"><span className="client-next-icon"><ArrowRight size={16} /></span><div><span className="client-section-kicker">DEPOIS DO ACEITE</span><h2>Próximo passo</h2><p>{previewScope.nextStep}</p></div></section><Button className="btn-primary preview-sign-button" onClick={onSign}>Assinar e aceitar proposta <ArrowRight size={15} /></Button></div></Modal>
  )
}

